"""Full-flow runner: execute every documented command as a checked subprocess.

Each step runs in a fresh interpreter (reloads and imports really happen), its
stdout and stderr go to ``logs/<step>.log``, a non-zero exit aborts the run, and a
manifest records argv, durations, digests and the isolation proof for the
calibration fit. The manifest is written even when a step fails, so the evidence
stays recoverable.

The data step has two modes. With ``data_directory`` unset the four splits are
generated by the ``data`` subcommand; with ``data_directory`` set the four files
are loaded with the same validation the ``validate-data`` command uses, proven
disjoint, and copied verbatim into ``<out>/data`` — nothing is regenerated. A
driving program can pass ``before_step`` to react to each step before it runs and
``on_step`` to see the stdout of each step that completed successfully.
"""

from __future__ import annotations

import datetime
import hashlib
import importlib.metadata
import json
import os
import platform
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

from . import __version__
from .dataset import (
    describe,
    load_splits,
    refuse_nonempty_directory,
    require_disjoint,
)

REPO_ROOT = Path(__file__).resolve().parents[2]


def _documented(module: str, *arguments: str) -> str:
    return " ".join(["uv", "run", "python", "-m", module, *arguments])


def _argv(module: str, *arguments: str) -> list[str]:
    return [sys.executable, "-m", module, *arguments]


class StepFailed(RuntimeError):
    """Raised when a subprocess step exits non-zero."""


class Violation(RuntimeError):
    """Raised when a gate check on a step's output fails."""


def environment_snapshot() -> dict[str, object]:
    torch_error: str | None = None
    try:
        import torch
    except Exception as error:  # pragma: no cover - environment is broken
        torch = None  # type: ignore[assignment]
        torch_error = f"{type(error).__name__}: {error}"
    packages: dict[str, str] = {}
    for distribution in importlib.metadata.distributions():
        name = (distribution.metadata.get("Name") or "").strip()
        version = distribution.version
        if name:
            packages[name.lower()] = version
    return {
        "python": platform.python_version(),
        "implementation": platform.python_implementation(),
        "platform": platform.platform(),
        "torch": torch_error if torch is None else getattr(torch, "__version__", "unknown"),
        "torch_cuda": bool(torch and torch.cuda.is_available()),
        "torch_mps": bool(torch and getattr(torch.backends, "mps", None)
                          and torch.backends.mps.is_available()),  # type: ignore[attr-defined]
        **packages,
    }


class RunState:
    def __init__(
        self,
        out: Path,
        device: str,
        before_step: Callable[[str, str, list[str]], None] | None = None,
        on_step: Callable[[str, str], None] | None = None,
    ) -> None:
        self.out = out
        self.device = device
        self.before_step = before_step
        self.on_step = on_step
        self.steps: list[dict[str, object]] = []
        self.started_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.hash_seed = os.environ.get("PYTHONHASHSEED", "randomized")

    def log_path(self, name: str) -> Path:
        path = self.out / "logs" / f"{name}.log"
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def run(
        self,
        name: str,
        module: str,
        arguments: list[str],
    ) -> str:
        argv = _argv(module, *arguments)
        documented = _documented(module, *arguments)
        log_path = self.log_path(name)
        started = datetime.datetime.now(datetime.timezone.utc).isoformat()
        if self.before_step is not None:
            self.before_step(name, module, arguments)
        completed = subprocess.run(
            argv, cwd=REPO_ROOT, capture_output=True, text=True, env=os.environ
        )
        seconds = round(time_since(started), 2)
        header = (
            f"# step={name} started={started} exit={completed.returncode} seconds={seconds}\n"
            f"# documented: {documented}\n"
            f"# argv: {json.dumps(argv)}\n"
            f"# cwd: {REPO_ROOT} pytorch-hash-seed: {self.hash_seed}\n"
        )
        log_path.write_text(
            header + "\n----- stdout -----\n" + completed.stdout
            + "\n----- stderr -----\n" + completed.stderr,
            encoding="utf-8",
        )
        entry: dict[str, object] = {
            "name": name,
            "documented": documented,
            "argv": argv,
            "exit_code": completed.returncode,
            "seconds": seconds,
            "log": _rel(log_path),
            "log_sha256": hashlib.sha256(log_path.read_bytes()).hexdigest(),
        }
        self.steps.append(entry)
        if completed.returncode != 0:
            tail = "\n".join(completed.stderr.strip().splitlines()[-8:])
            raise StepFailed(
                f"step {name!r} exited {completed.returncode}; "
                f"see {log_path}. stderr tail:\n{tail}"
            )
        if self.on_step is not None:
            self.on_step(name, completed.stdout)
        return completed.stdout


def time_since(iso_start: str) -> float:
    started = datetime.datetime.fromisoformat(iso_start)
    return (datetime.datetime.now(datetime.timezone.utc) - started).total_seconds()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:  # an --out outside the repository
        return str(path)


def _artifact(path: Path, label: str, extra: dict[str, object] | None = None) -> dict[str, object]:
    entry: dict[str, object] = {
        "label": label,
        "path": _rel(path),
        "bytes": path.stat().st_size,
        "sha256": _sha256(path),
    }
    if extra:
        entry.update(extra)
    return entry


def _read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def first_test_row(path: Path) -> dict[str, object]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                return json.loads(line)
    raise Violation(f"test split {path} is empty")


def _copy_external_splits(source: Path, destination: Path) -> dict[str, object]:
    """Validate a provided split directory, copy its four files, report their digests.

    ``load_splits`` applies the same per-row validation as ``validate-data`` (JSON
    object, non-blank context and options, unique options, integer label in range)
    and ``require_disjoint`` refuses empty splits and shared contexts. The files are
    then copied byte for byte — the digests in the report are taken from the copies
    in ``destination``, so a manifest quoting them describes what was actually
    trained on.
    """
    splits = load_splits(source)
    shared = require_disjoint(splits)
    destination.mkdir(parents=True, exist_ok=True)
    for name in splits:
        shutil.copyfile(source / f"{name}.jsonl", destination / f"{name}.jsonl")
    return {
        "seed": None,
        "sizes": {name: len(rows) for name, rows in splits.items()},
        "splits": {
            name: describe(destination / f"{name}.jsonl", rows)
            for name, rows in splits.items()
        },
        "shared_contexts": shared,
        "disjoint": all(count == 0 for count in shared.values()),
        "generator": "external directory, copied verbatim after validation",
        "source_directory": str(source),
    }


def run_all(
    out_root: Path,
    *,
    device: str,
    sizes: dict[str, int],
    data_seed: int,
    train_seed: int,
    width: int,
    rank: int,
    context_tokens: int,
    option_tokens: int,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    predict_context: str | None,
    predict_options: list[str] | None,
    force: bool = False,
    encoder: str = "tiny",
    hf_model: str = "Qwen/Qwen2.5-0.5B",
    hf_revision: str | None = None,
    data_directory: Path | None = None,
    eval_batch_size: int = 64,
    before_step: Callable[[str, str, list[str]], None] | None = None,
    on_step: Callable[[str, str], None] | None = None,
) -> int:
    # One absolute root for everything, decided here rather than in the caller: the
    # step subprocesses run with cwd=REPO_ROOT, so a relative --out resolved against
    # any other working directory would create the parent directory in one place and
    # write the children's files in another.
    out = Path(out_root)
    if not out.is_absolute():
        out = Path(REPO_ROOT) / out
    out = out.resolve()
    refuse_nonempty_directory(out, force, "the run outputs")
    out.mkdir(parents=True, exist_ok=True)
    data_dir = out / "data"
    checkpoint = out / "model.pt"
    temperature_file = out / "temperature.json"
    evaluation_file = out / "evaluation.json"
    predictions_file = out / "predictions.json"
    checks_file = out / "checks.json"
    data_report_file = out / "data-manifest.json"
    state = RunState(out, device, before_step=before_step, on_step=on_step)
    source_dir: Path | None = None
    if data_directory is not None:
        source_dir = Path(data_directory)
        if not source_dir.is_absolute():
            source_dir = Path(REPO_ROOT) / source_dir
        source_dir = source_dir.resolve()
        # Copying a source that lives inside --out means reading files this run is
        # about to overwrite (force) or write beside; the copy would be either a
        # self-copy of the destination or a silent re-use of a previous run.
        if source_dir == out or out in source_dir.parents:
            raise ValueError(
                f"--data-directory {source_dir} is inside the run output {out}; "
                "point it at data outside the directory run-all writes to"
            )
    manifest: dict[str, object] = {
        "schema": 1,
        "status": "running",
        "started_utc": state.started_utc,
        "package_version": __version__,
        "repo_root": str(REPO_ROOT),
        "device": device,
        "pytorch_hash_seed": state.hash_seed,
        "model": {
            "encoder": encoder,
            "hf_model": hf_model,
            "hf_revision": hf_revision,
            "eval_batch_size": eval_batch_size,
            **({"lora_rank": 16, "lora_alpha": 32, "head_learning_rate": 0.0005,
                "scheduler": "OneCycleLR"} if encoder == "lora" else {}),
        },
        "data": {
            "seed": data_seed,
            "sizes": dict(sizes),
            "train_seed": train_seed,
        },
        "hyperparameters": {
            "width": width, "rank": rank,
            "context_tokens": context_tokens, "option_tokens": option_tokens,
            "epochs": epochs, "batch_size": batch_size, "learning_rate": learning_rate,
        },
    }
    try:
        state.run("check", "jev_course.cli", ["check", "--json-out", str(checks_file)])
        if not _read_json(checks_file).get("ok"):
            raise Violation("self-checks failed; refuse to continue")

        if source_dir is None:
            state.run(
                "data", "jev_course.cli",
                [
                    "data", "--out", str(data_dir),
                    "--train", str(sizes["train"]),
                    "--validation", str(sizes["validation"]),
                    "--calibration", str(sizes["calibration"]),
                    "--test", str(sizes["test"]),
                    "--seed", str(data_seed),
                    "--json-out", str(data_report_file),
                    *(["--force"] if force else []),
                ],
            )
            data_report = _read_json(data_report_file)
        else:
            data_report = _copy_external_splits(source_dir, data_dir)
            data_report_file.write_text(json.dumps(data_report, indent=2) + "\n", encoding="utf-8")
            state.steps.append({
                "name": "data",
                "documented": None,
                "argv": None,
                "exit_code": 0,
                "log": None,
                "source_directory": str(source_dir),
                "dest_directory": str(data_dir),
            })
        if not data_report.get("disjoint") or any(
            count for count in data_report["shared_contexts"].values()
        ):
            raise Violation(f"data splits are not disjoint: {data_report['shared_contexts']}")
        for name in ("train", "validation", "calibration", "test"):
            if data_report["splits"][name]["rows"] < 1:
                raise Violation(f"split {name} is empty")
        manifest["data"] = {**manifest["data"], **data_report}

        train_args = [
            str(data_dir / "train.jsonl"),
            "--validation", str(data_dir / "validation.jsonl"),
            "--output", str(checkpoint),
            "--encoder", encoder,
            "--width", str(width), "--rank", str(rank),
            "--context-tokens", str(context_tokens), "--option-tokens", str(option_tokens),
            "--epochs", str(epochs), "--batch-size", str(batch_size),
            "--learning-rate", str(learning_rate),
            "--device", device, "--seed", str(train_seed),
        ]
        # The model and revision flags only mean something to the huggingface
        # encoder; jevlike.train carries its own defaults for the tiny one, and
        # --hf-revision stays off the command line unless a revision was named.
        if encoder in ("hf", "lora"):
            train_args += ["--hf-model", hf_model]
            if hf_revision is not None:
                train_args += ["--hf-revision", hf_revision]
        state.run("train", "jevlike.train", train_args)
        if not checkpoint.exists():
            raise Violation(f"train step did not create {checkpoint}")

        state.run(
            "eval", "jevlike.eval",
            [
                str(checkpoint), str(data_dir / "test.jsonl"),
                "--batch-size", str(eval_batch_size), "--device", device,
            ],
        )

        state.run(
            "fit", "jev_course.cli",
            [
                "fit", str(checkpoint), str(data_dir / "calibration.jsonl"),
                "--output", str(temperature_file), "--device", device,
                "--batch-size", str(eval_batch_size),
            ],
        )
        fit_report_ = _read_json(temperature_file)
        fitted_digest = fit_report_["fitted_on"]["file_sha256"]
        calibration_digest = data_report["splits"]["calibration"]["file_sha256"]
        test_digest = data_report["splits"]["test"]["file_sha256"]
        temperature = float(fit_report_["temperature"])
        if not temperature > 0.0:
            raise Violation(f"fit produced a non-positive temperature {temperature}")
        if fitted_digest != calibration_digest:
            raise Violation(
                "the fit was not run on the calibration split: "
                f"fitted {fitted_digest[:12]}… != calibration {calibration_digest[:12]}…"
            )
        manifest["calibration_isolation"] = {
            "fitted_on": fit_report_["fitted_on"]["path"],
            "fitted_digest_matches_calibration": fitted_digest == calibration_digest,
            "fitted_digest_differs_from_test": fitted_digest != test_digest,
            "temperature": temperature,
        }

        state.run(
            "test", "jev_course.cli",
            [
                "test", str(checkpoint), str(data_dir / "test.jsonl"),
                "--temperature", str(temperature_file),
                "--device", device, "--json-out", str(evaluation_file),
                "--batch-size", str(eval_batch_size),
            ],
        )
        evaluation = _read_json(evaluation_file)
        after = evaluation["test_after"]
        if after["binned_examples"] != after["examples"]:
            raise Violation("ECE bins did not cover every test row")
        if evaluation["test"]["file_sha256"] != test_digest:
            raise Violation("the evaluated split is not the test split in the data report")
        manifest["evaluation"] = {
            "test_before_nll": evaluation["test_before"]["nll"],
            "test_after_nll": after["nll"],
            "test_accuracy_before": evaluation["test_before"]["accuracy"],
            "test_accuracy_after": after["accuracy"],
            "shuffled_context_control_top1": evaluation["shuffled_context_control"]["top1"],
            "raw_context_top1": evaluation["raw_context"]["top1"],
            "examples": after["examples"],
        }

        label: int | None = None
        if predict_context is None or not predict_options:
            row = first_test_row(data_dir / "test.jsonl")
            predict_context = predict_context or str(row["context"])
            predict_options = predict_options or [str(option) for option in row["options"]]
            label = int(row["label"])
        predict_args = [
            "predict", str(checkpoint),
            "--temperature", str(temperature_file),
            "--context", predict_context,
            "--device", device, "--permute-check",
            "--json-out", str(predictions_file),
        ]
        for option in predict_options:
            predict_args += ["--option", option]
        if label is not None:
            predict_args += ["--label", str(label)]
        state.run("predict", "jev_course.cli", predict_args)
        predictions = _read_json(predictions_file)
        probability_sum = float(predictions["probability_sum"])
        permutation = predictions["permutation_check"]
        if abs(probability_sum - 1.0) > 1e-6:
            raise Violation(f"predicted probabilities sum to {probability_sum}, not 1")
        if not predictions["options_unique"]:
            raise Violation("prediction step collapsed duplicate options")
        if not permutation["stable"] and permutation["top_gap"] > 1e-9:
            raise Violation(f"reordering options changed the choice: {permutation}")
        manifest["predictions"] = {
            "context": str(predictions["context"])[:80],
            "options": list(predictions["options"]),
            "choice": str(predictions["choice"]),
            "probability_sum": probability_sum,
            "permutation_stable": bool(permutation["stable"]),
            "max_probability_drift": permutation["max_probability_drift"],
        }

        manifest["environment"] = environment_snapshot()
        manifest["status"] = "ok"
        manifest["finished_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    except Exception as error:
        manifest["status"] = "failed"
        manifest["failure"] = f"{type(error).__name__}: {error}"
    finally:
        manifest["steps"] = state.steps
        manifest["artifacts"] = []
        for label, path in (
            ("check_report", checks_file),
            ("data_manifest", data_report_file),
            ("checkpoint", checkpoint),
            ("temperature", temperature_file),
            ("evaluation", evaluation_file),
            ("predictions", predictions_file),
        ):
            if path.exists():
                manifest["artifacts"].append(_artifact(path, label))
        for log in sorted((out / "logs").glob("*.log")):
            manifest["artifacts"].append(_artifact(log, f"log:{log.stem}"))
        manifest_file = out / "manifest.json"
        manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(json.dumps({"manifest": _rel(manifest_file),
                          "status": manifest["status"]}, indent=2))
    return 0 if manifest["status"] == "ok" else 1